resolver: lts-13.22

packages:
  - .

extra-deps:
  # --- Missing from Stackage --- #
  - QuickCheck-GenT-0.2.0
  - bloomfilter-2.0.1.0
  - ed25519-donna-0.1.1
  - fake-0.1.1.2
  - fast-builder-0.1.0.1
  - loglevel-0.1.0.0
  - merkle-log-0.1.0.0
  - paths-0.2.0.0
  - prettyprinter-convert-ansi-wl-pprint-1.1
  - scheduler-1.1.0
  - strict-tuple-0.1.2
  - yet-another-logger-0.3.1

  # --- Forced Dependencies --- #
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2  # Due to megaparsec 7
  - sbv-8.2

  # --- Forced Upgrades --- #
  - aeson-1.4.3.0
  - massiv-0.3.2.0
  - servant-0.16.0.1
  - servant-server-0.16
  - servant-client-0.16
  - servant-client-core-0.16

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/pact.git
    commit: 0915aff9eed762b2ee58c648d900bc619e6fff96
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
